spin_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
trigger = { type = "http", base = "{{http-base}}" }
version = "0.1.0"

[[component]]
id = "{{project-name | kebab_case}}"
files = [ { source = "./src", destination = "/" } ]
# for outgoing HTTP (see spin:http_fetch/3)
allowed_http_hosts = [] # "insecure:allow-all" is a special unsafe value to allow any host
# access to key-value stores (see spin:store_* predicates)
key_value_stores = ["default"]
[component.source]
url = "https://github.com/guregu/trealla/releases/download/v0.14.3/libtpl-spin.wasm"
digest = "sha256:91f95706abd4b4a39468106b015bda0ecda6798e5ee60ab43a9003350ba2d9db"
[component.trigger]
route = "{{http-path}}"
